hd-zero/hdzero-goggle

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitattributes
- .vscode/tasks.json
- README.md
- setup.sh
- add support for the [vscode devcontainer integration](https://code.visualstudio.com/docs/devcontainers/containers)
- extend `setup.sh` to take care of the bootstrap process
- update readme
> add devcontainer setup

- src/core/elrs.c
- src/core/input_device.c
- src/core/main.c
- src/core/osd.c
- src/core/statusbar.c
- src/core/thread.c
- src/driver/dm5680.c
- src/page/page_common.h
- src/page/page_imagesettings.c
- src/page/page_scannow.c
- src/page/page_source.c
This PR creates and uses an enum for the input source item.
> Add enum for source

- src/core/main.c
- src/page/page_scannow.c
- src/page/page_source.c
Update `last_source` ini setting to use enum missed in previous PR.
> Update last_source to use enum

- src/ui/page_record.c
1. Fixed spelling error "Formating -> Formatting"
2. Updated formatting SD Card confirmation message to be clearer
3. Updated MP4 format message to be clearer
> page_record label/message updates

- src/ui/page_autoscan.c
- src/ui/page_connections.c
- src/ui/page_fans.c
- src/ui/page_headtracker.c
- src/ui/page_imagesettings.c
- src/ui/page_power.c
- src/ui/page_record.c
- src/ui/page_source.c
- src/ui/page_version.c
- src/ui/ui_image_setting.c
- src/ui/ui_statusbar.c
These are various improvements to the strings. Keep in mind, that this isn't tested as I haven't gotten my googles yet.
Especially the statusbar change might cause problems, if it's too long now, but hopefully it's not, that's a place where it's really bugging me.
The correct handling of the back button, would probably also be a custom item, with a button pointing back. Basically similar to how we do the selection item. But this is still an improvement for now.
> Cleanup strings

- src/core/elrs.c
- src/core/elrs.h
- src/driver/esp32.c
- src/ui/page_connections.c
- src/ui/page_version.c
This PR adds a few QoL improvements to the ELRS integration.
There is a matching ELRS backpack firmware update to make these function, available from https://drive.google.com/file/d/1dnzd_SRU7x-fBwOIsF9839cYs2NQNO9N/view?usp=share_link
1. When entering the Firmware page, if the ELRS backpack is ON then the firmware version/branch is displayed next to the "update" button.
2. When entering the "Connections" page, the "Binding" button will query the backpack and display the currently bound UID, or "Not bound".
> ELRS quality of life improvements

- src/core/MadgwickAHRS.c
- src/core/MadgwickAHRS.h
- src/core/ht.c
- src/core/ht.h
- src/core/main.c
- src/ui/page_headtracker.c
Just some cleanup so we can avoid issues later on
> Head tracking cleanup

- src/core/main.c
Use `ini_getl` in places where we were reading a string and using `atoi` to convert to a number anyway.
> Cleanup loading of ini file

- README.md
Add official social links to the readme so they are easier to find.
> Add discord and facebook links from official website to readme

- src/core/battery.c
- src/core/battery.h
- src/core/elrs.c
- src/core/osd.c
- src/core/thread.c
- src/driver/mcp3021.c
- src/driver/mcp3021.h
- src/ui/page_power.c
- src/ui/page_power.h
- src/ui/ui_statusbar.c
- src/ui/ui_statusbar.h
> Battery Refactor

- src/ui/page_playback.c
Adds a not at the bottom of the playback screen about how to exit the page.
> Add note about exiting playback page

- src/core/elrs.c
- src/core/elrs.h
caused by some prior changes (sorry!) the elrs backpack could trigger recording while the current menu level != video.
PR rectifies this behaviour, first commit is formatting.
> disallow elrs backpack from recording while in the menu

- src/core/settings.c
Changed the initialization of the default settings struct to a designated initializer, makes it a lot longer but safer, especially when changing things.
> Refactor default setting struct initialization

- mkapp/app/setting.ini
- src/core/app_state.c
- src/core/main.c
- src/core/osd.c
- src/core/settings.c
- src/core/settings.h
- src/ui/page_autoscan.c
- src/ui/page_common.h
- src/ui/page_connections.c
- src/ui/page_fans.c
- src/ui/page_headtracker.c
- src/ui/page_record.c
- src/ui/page_source.c
- src/ui/ui_statusbar.c
replace some hardcoded values with enums
improve some enum names
fix misplaced bracket in ui_statusbar
> Refactor settings to standardise boolean saving

- src/core/main.c
- src/core/osd.c
- src/core/osd.h
- src/ui/page_common.h
Glyphs on SD card to be used, should exist as: /resource/OSD/GOGGLE and /resource/OSD/GOGGLE/FHD for 720p and 1080p respectively.  Kudos to bkleiner (Hanfer) for a lot of the code base for this!
> Embedded OSD Glyphs optional SD CARD Location

- mkapp/app/script/rc.sh
- mkapp/app/services/install.sh
Provides user the ability to install their own 3rd party services via the SD Card.  Refer to hdzero-goggle-services repo for more information.  An ntpclient will soon be available via hdzero-goggle-services as well.
https://github.com/SumolX/hdzero-goggle-services/tree/master
> hdzero-goggle-services install and startup scripts

- README.md
Enhance success for initial Emulator build and usage.
> Emulator Build/Usage README.md enhancement

- src/core/settings.c
Default saturation is 28
Default contrast is 25
> modify saturation & contrast default value

- .gitignore
- src/core/settings.c
> Ignore build emu folder

- src/ui/ui_statusbar.c
This breakage was introduced during WiFi Page introduction.  Restored proper loading of fonts and consolidated logic.
> Fixed ui_statusbar font loading issue.

- src/ui/page_playback.c
This code is COMPLETELY UNTESTED as I am unable to get building working on my (Windows 10) PC so far.
However, the code seems pretty straightforward (Although I am not a C coder, so could have completely mis-understood the code) so I thought it worth submitting a PR anyway
> Add wraparound to playback menu (Fix #275)

- mkapp/app/script/chkfixsd.sh
- mkapp/app/script/formatsd.sh
Fix sdcard scripts to support correct sdcard partition.
Add compatibility with sdcards formatted without partition table by previous scripts.
> fix sdcard integrity check and format scripts

- src/driver/hardware.c
> fix video timing

- src/core/osd.c
- src/driver/dm6302.c
- src/driver/dm6302.h
- src/ui/page_scannow.c
- src/ui/page_scannow.h
> suppoer E1 and F1 channel

- src/ui/page_input.c
Fixes #384 
@pitts-mo Can you please verify that this PR fixes your issue? I did a quick code review and found this line that should cause it.
@ligenxxxx This PR should be included in the next release, or at least as soon as #367 is released as well.
> Fix initial roller function setting item

- src/ui/page_storage.c
> Clear DVR folder on storage page

- src/driver/TP2825.c
It should have been merged in 9.4.0
> Inverse  TP2825 CLKO pin polarity

- src/core/dvr.c
https://discord.com/channels/880782999006883870/880801204018483232/1302597887385010196
> sleep 100ms before rec start

- src/driver/hardware.c
Set vdpo clock driver strength to level 2
> Fix oled flickering during playback
