- CMakeLists.txt
```
hdzero-goggle/toolchain/bin/../lib/gcc/arm-openwrt-linux-muslgnueabi/6.4.1/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: cannot find -lmedia
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/HDZGOGGLE.dir/build.make:1404: HDZGOGGLE] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/HDZGOGGLE.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
~~+ whitespace cleanups~~
> cmake: media library dependency fixed to avoid possible linking error 

- src/core/thread.c
- src/core/thread.h
this new approach should be faster and more reliable, works by comparing the dev (as in filesystem device) ids of the mountpoint and the parent of the mountpoint.
> sdcard: use dev_ids to check for presence

- src/core/main.c
- src/page/page_autoscan.c
- src/page/page_common.h
Changes the "Auto Scan" option to `On`/`Last`/`Off`
- `On` does the auto scan
- `Last` tunes to last channel
- `Off` just displays the main menu on the scan page
Fixes #23
> Change autoscan to on/last/off

- src/core/main_menu.c
- src/page/page_connections.c
- src/page/page_connections.h
- src/page/page_version.c
Moves the backpack flashing to the "Firmware" menu, as previously suggested.
Also adds colors to "Success", "FAILED" and "Timeout" status values.
Button text returns back to _default_ value when cursor is moved.
> Backpack cleanup

- src/core/input_device.c
- src/ui/page_autoscan.c
- src/ui/page_autoscan.h
- src/ui/page_common.c
- src/ui/page_common.h
- src/ui/page_connections.c
- src/ui/page_connections.h
- src/ui/page_fans.c
- src/ui/page_fans.h
- src/ui/page_headtracker.c
- src/ui/page_headtracker.h
- src/ui/page_imagesettings.c
- src/ui/page_imagesettings.h
- src/ui/page_playback.c
- src/ui/page_playback.h
- src/ui/page_power.c
- src/ui/page_power.h
- src/ui/page_record.c
- src/ui/page_record.h
- src/ui/page_scannow.c
- src/ui/page_scannow.h
- src/ui/page_source.c
- src/ui/page_source.h
- src/ui/page_version.c
- src/ui/page_version.h
- src/ui/ui_main_menu.c
- src/ui/ui_main_menu.h
this pr reworks the page pack interface to allow specifying handler functions for different page interactions,
this moves the complexity out of the main menu file and into the page files where the rest of logic usually resides.
this allows for generic handling of all pages in main_menu, greatly simplifying the process of adding new pages.
additionally:
- formats all page files 
- tidies some type definitions
for review i recommend skipping the first commit, it does not change any logic, but only formats the file according to the clang-format file
> page pack refactor

- src/core/osd.c
The link-locked icon was created with the wrong image in the init function, then was loads the correct image each time the icon is displayed, when it should really just be hiding/showing the existing icon.
> Fix for link-locked icon

- CMakeLists.txt
- lib/esp-loader/CMakeLists.txt
- lib/log/CMakeLists.txt
- lib/lvgl/CMakeLists.txt
- lib/minIni/CMakeLists.txt
- toolchain.cmake
Allows 3rd party libraries build with common settings.
> Common CFLAGS are now stored in toolchain.cmake

- src/driver/hardware.c
The default FIR filter causes the OSD's chroma border to spread, eventually causing the OSD border to display the wrong color.
`dispw` will overwrite `0x06542018` to `0x00000022`, and `aww` needs to be run after `dispw` is executed.
> Disable horizontal chroma fir filter for vdpo

- CMakeLists.txt
- src/core/MadgwickAHRS.c
- src/core/defines.h
- src/core/ht.c
- src/core/ht.h
- src/core/input_device.c
- src/core/main.c
- src/core/thread.c
- src/core/thread.h
- src/ui/page_common.c
- src/ui/page_common.h
- src/ui/page_headtracker.c
- src/ui/page_headtracker.h
- src/util/math.c
- src/util/math.h
Implementation of Head Tracking.
The head tracker in the HDZero goggles outputs the PPM signal on the HT port on the goggles with the following channel layout
- Pan -> Channel 0 (TR1 in EdgeTX)
- Tilt -> Channel 1 (TR2 in EdgeTX)
- Roll - Channel 2 (TR3 in EdgeTX)
In the goggles "Head Tracking" page the "Tracking" option should be set to "On", the the goggles should be resting on a level surface and the "Calibrate" option should be selected. I find that resting them on a book on the left and right side, with the face plate above the desk gives the best results.
The "Max Angle" option is used to set the angular limits for the head tracker, i.e. how far your head moves to reach full deflection on the PPM signal. The best way to do this is to first get you head in natural resting position …
> Implement Head Tracking

- CMakeLists.txt
- lib/lvgl/lvgl/lv_conf.h
- src/core/msp_displayport.c
- src/core/msp_displayport.h
- src/ui/ui_porting.c
- src/util/time.c
- src/util/time.h
- adds optimization flags to ensure msp displayport processing can keep up
- fixes bug introduced in #94 where lqi second counter wouldn't get updated.
> fix vlq indicator

- src/core/osd.c
Antenna glyph ordering confusing and changed to left to right 1, 2, 3, 4 when viewing goggles top down.
> Antenna OSD order

- src/core/common.c
- src/core/common.hh
- src/core/elrs.c
- src/core/input_device.c
- src/core/input_device.h
- src/core/osd.c
- src/core/osd.h
- src/core/thread.c
- src/driver/dm5680.c
- src/ui/page_autoscan.c
- src/ui/page_connections.c
- src/ui/page_fans.c
- src/ui/page_focus_chart.c
- src/ui/page_headtracker.c
- src/ui/page_imagesettings.c
- src/ui/page_playback.c
- src/ui/page_playback.h
- src/ui/page_power.c
- src/ui/page_record.c
- src/ui/page_scannow.c
- src/ui/page_source.c
- src/ui/page_version.c
- src/ui/ui_main_menu.c
- src/ui/ui_main_menu.h
- src/util/file.c
- src/util/file.h
- adds function to control dvr directly
- adds right button handlers to pages
- reworks playback sdcard scan
- marks clip as "hot" on right button
> Feature hot clip

- src/core/elrs.c
As reported by cjohnstone87 on discord, if you are recording a channel and you change channel via the backpack, the recording contains garbage after the channel change. When changing channel via the OSD it stops the recording before changing channel.
This PR changes the backpack behaviour to be the same as the OSD.
> Stop DVR when changing channel via backpack

- mkapp/mkapp_ota.sh
for some reason the short versions of the parameters to the mkfs.jffs2 command do not work reliably
adjusts the app size to 8MB, which should give us plenty of headroom, as the compressed version of the app currently is 2.2MB.
> fix app size

- src/ui/page_autoscan.c
- src/ui/page_connections.c
This PR just aligned the start columns of these pages to be consistent with all the other pages. It was a bit jarring scrolling through and seeing these ones jump.
> Alignment of connections and auto-scan pages

- lib/log/CMakeLists.txt
- lib/log/include/log/log.h
- lib/log/src/log.c
- src/core/main.c
- src/core/self_test.c
- src/core/self_test.h
Carl made me aware that the "self test" feature stopped working. That previously hooked into their flavor of `Printf` and was lost during the log refactor.
This PR re-adds this functionality.
> Fix self test logging

- mkapp/mkapp_ota.sh
Rather that using the `--pad` parameter to the `mkfs.jffs2` command, which cause the build to take 4 minutes in a devcontainer on MacOS, likely because of the way the directory is volume mounted.
If the filesystem is greater than the the configured `APP_SIZE` in the script, then a message is printed and script exits with exit code 1, causing the build to fail.
> Fail build if firmware exceeds set size

- src/core/ht.c
- src/core/ht.h
- src/core/main.c
There was an intermittent problem when the OLED off/on is called from the timer thread where the OLED on would not always work causing the screens to stay off.
This PR changes that behaviour by just setting a flag in the timer thread, and the `detect_motion` call is now done from the main thread which perform the OLED changes if there was motion or not.
Prior to this fix I could easily get the OLED wake to fail within a couple of tries, but after this I have performed the sleep/wake well over 10 times without a problem.
> Fixes OLED wake from motion detect

- src/core/input_device.c
Implements a double-click handler for the right button (when in video mode) that resets the centre position of the head tracker.
The second commit is a code reformat only.
> Double click right button to reset HT centre point

- mkapp/app/setting.ini
- src/core/battery.c
- src/core/battery.h
- src/core/main.c
- src/ui/page_common.h
- src/ui/page_power.c
- src/ui/page_power.h
- src/ui/ui_statusbar.c
Added a toggle to the power settings page to choose whether the osd shows the total battery voltage or the average voltage per cell.
I wanted to make it obvious which mode is active, so "/C" is added to the old format when cell average mode is active, if someone has a better idea let me know.
e.g.:
"Total" mode:       4S 15.6V
"Cell Avg." mode: 4S 3.9V/C
Would appreciate if someone could test the pr on their goggles, don't have mine yet.
Resolves #68
> Add option to display average cell voltage in osd

- src/core/elrs.c
- src/core/elrs.h
- src/core/ht.c
- src/util/math.h
This PR builds on top the head tracking and ELRS backpack work done previously.
To test this PR you currently need to flash the  HDzero goggles with this PR, the HDzero goggle and TX module backpack need to be flashed with the backpack wireless head tracking PR (https://github.com/ExpressLRS/Backpack/pull/83) and the TX module also needs to be flashed with the wireless head tracking PR (https://github.com/ExpressLRS/ExpressLRS/pull/2060).
Once that is done, there will be an option in the ExpressLRS Lua "Backpack" menu that allows you to configure which channels Pan/Tilt/Roll are mapped to when being sent to the ELRS receiver.
EDIT: After some feedback, I've added an "enable" channel option in the ELRS Lua script, which allows the user to disable/enable the head tracker via a switch. Each …
> Wireless Head Tracking

- src/core/osd.c
As mentioned on discord, after flying HD, then switching to analog the OSD is not cleared.
Also, mentioned on discord when switching HD channels the OSD is not cleared.
The problem is that the OSD buffer is cleared by calling `osd_clear`, but then OSD thread was not signalled to copy the buffer to the shadow buffer (used for actual display). This fix adds a call to `osd_signal_update` in the `osd_clear` function so the OSD thread copies the data to the shadow buffer.
> Fix OSD not being cleared properly

- src/ui/page_playback.c
added option to delete selected clip by long pressing right button on page_playback
> delete selected clip

- mkapp/app/setting.ini
- src/core/main.c
- src/core/osd.c
- src/core/osd.h
- src/ui/page_common.c
- src/ui/page_common.h
Refactored OSD code to allow for individual element positioning and visibility settings (with settings saving x,y for both 4x3 and 16x9 modes) in preparation for a dedicated OSD settings page.
No (intentional) UI changes, besides changing the order of some OSD elements.
Added "g_setting_defaults" const setting_t struct instance to hold defaults for all settings values in one place.
Gonna need help testing this one, if the approach looks good.
> refactor, add settings for osd element positioning

- src/core/elrs.c
- src/core/elrs.h
- src/core/osd.c
Adds support for receiving MSP commands to add the the OSD overlay. And also implements the buzzer command over MSP as well. 
The current VTx OSD takes precedence, so if the ELRS elements are put in places that are used then the existing ones are displayed.
This is in preparation for other backpack features that are in the works.
To test you should flash https://github.com/ExpressLRS/Backpack/pull/84 to the backpack. Also flash an ESP32 with the DEBUG_TX_Backpack and you can use the `osd_test.py` script in the Backpack repo for sending text to the goggle OSD.
> Add ELRS OSD and buzzer support

- src/record/main.c
re-reads the record format configuration regardless of current record state.
tries to address #180, however with no way to reproduce it, we are pretty much in the dark whether or not this does anything
> record: fetch configuration on every record attempt

- src/core/elrs.c
- src/core/elrs.h
As outlined in ExpressLRS/Backpack#86 this PR adds the ability to update the system and RTC clock using the ELRS backpack that connects to the home WiFi network to access a NTP server. 
To test this you need to flash the onboard backpack with the Backpack PR and follow the instructions for configuring and updating the clock.
> Add clock update function via ELRS backpack

- src/core/osd.c
After the merge of 9.0.3 the ELRS OSD overlay was missed out of the merge. This just reinstates that functionality.
> Reinstate ELRS OSD overlay

- CMakeLists.txt
Requires newer version of CMake, however we can still leverage the ${SDL2_LIBRARIES}:
```
New in version 3.19.
This module defines the following [IMPORTED](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED.html#prop_tgt:IMPORTED) target:
SDL::SDL
The SDL library, if found
```
> CMakeLists.txt v3.10 does not support SDL2::SDL2

- src/core/msp_displayport.c
- src/core/msp_displayport.h
- src/core/osd.c
- Reload osd font when video resolution(1080P<->720P) changed.
- Fixed the problem that osd_shadow cannot be fully cleared when switching osd font.
> Fix osd font loading

- src/core/common.c
- src/core/common.hh
- src/core/main.c
- src/driver/mcp3021.c
- src/driver/mcp3021.h
- src/driver/nct75.c
- src/ui/page_power.c
- src/ui/page_power.h
Added hw_revision_t to common.
Restructured startup behavior to ensure hardware comms was available prior to deriving revision type.
Batch 1 users will not be shown softswitch option in power as it is only available on newer hardware.
Tested on Batch 1 goggle and Emulator.  Will need feedback from Batch 2 goggle users prior to approving pull request.
> Softswitch only available on Batch 2 and greater

- CMakeLists.txt
- lib/live/CMakeLists.txt
the prebuilt `libliveMedia.a` was compiled without PIC enabled.
to prevent linker errors with other toolchains, the cmake file must enforce `no-pie` during linking of the executable.
> ensure rtspLive is compiled without PIE/PIC

- src/ui/ui_main_menu.c
Since the final output is 422, when the border width is 3:
- the left border is always a bit wider than the right border
- Left and right borders are colored differently.
Setting width to 2 fixes these issues.
> set menu border width from 3 pix to 2 pix

- src/core/main.c
- src/core/osd.c
- src/core/osd.h
- src/rtspLive/stream/version.h
- src/ui/page_focus_chart.c
- src/ui/page_playback.c
- src/ui/page_version.c
- src/ui/page_version.h
Emulator build failed to compile due to duplicate symbols.  Issue was found by Mart in Discord.
Fixed all warnings currently identified by GCC-11
Fixed resource loading of Playback Icon and Focus Chart
> Fixed various bugs that were identified in GCC11

- src/core/input_device.c
- src/core/input_device.h
- src/driver/dm5680.c
There is a 2 second delay displaying the "REC" icon when pressing the right button
This was introduced when the double-click handler was added for centring the head tracker. Because the `dm5680` thread would set a timeout for detecting the single-click vs double-click and the timer is handled in the main thread (along with the OSD and other things), and the `dvr_cmd` code has a forced 2 second sleep after calling the command to start/stop the dvr.  And so the OSD would not update for 2 seconds after the button was clicked.
Move the double-click detection code to the `dm5680` thread so the `dvr_cmd` is also called in that thread, as it was prior to the double-click detection code being added.
> Move double click detection to dm5680 thread

- CMakeLists.txt
Minor CMakeLists.txt cleanup and now treat warnings as errors for Release builds.
> Warnings are treat as errors moving forward

- src/ui/ui_osd_element_pos.c
When returning to the main menu from the osd element positioning preview with a long press *while a menu item is focused* (dropdown extended/slider selected), the previews' menu would be broken when entering it again. (and the dropdown remained on screen)
> Fix osd element pos preview UI not resetting correctly

- src/core/elrs.c
- src/core/elrs.h
- src/ui/page_elrs.c
Add the ability to cancel ELRS binding (which has a 2 minute timeout) by pressing the right button.
When binding starts, a small help text is shown about how to cancel the binding.
If the binding is cancelled, the ESP32 is powered off and on again and a the current bind UID is re-requested.
Also, the name of the Bind button was "ELRS" after the last reworking of this code, which was wrong, so that too was fixed.
> Clean up ELRS bind behaviour

- src/core/elrs.c
- src/core/ht.c
- src/core/main.c
- src/driver/beep.c
- src/driver/beep.h
- src/driver/gpio.c
- src/driver/gpio.h
- src/ui/page_version.c
- src/ui/ui_statusbar.c
This PR moves beep GPIO control to a separate thread so that beeps don't block and so can be made long enough to be audible. 😄 Calling parts of the system don't need to worry about it waiting anymore.
- The previous beep (via `beep()`) is only 500us (!) so just makes a little tap sound. The default beep is now 50ms, with a longer 200ms beep available for future use.
- `beep_dur` now takes milliseconds, rather than microseconds.
> Offload beep to new thread, make audible.

- src/ui/page_sleep.c
Go Sleep! exit behavior improvement.
Batch 2 goggles will now:
-force analog power off instead of setting analog power off.
-use existing analog power setting to restore analog power state when exiting sleep.
~~All goggle batches will now:
-attempt to resume live view immediately upon exit.~~
This is a good enough resolution for #267.
However, #230 still needs to be addressed and I still see it desirable to unify all power and state setting into a single location.
> Go Sleep! impovements -restore analog power state

- src/core/input_device.c
- src/core/osd.c
- src/core/settings.c
- src/core/settings.h
- src/ui/page_common.c
- src/ui/page_common.h
- src/ui/page_osd.c
Added a new option to the OSD page to set the startup visibility of the goggle OSD.
Closes #188
> Add option to set startup OSD visibility

- mkapp/app/script/wlan_stop.sh
- mkapp/app/services/scripts/dropbear_start.sh
- src/core/settings.c
- src/core/settings.h
- src/ui/page_common.h
- src/ui/page_wifi.c
Some users have started to receive their wifi modules and are unable to ssh into goggles.  This is due to a OS root password bug which relates to /etc/passwd and the shadowing of the password not being setup properly.
New 3rd Page has been added which allows users to configure the root password and enable/disable SSH access (defaults to disabled).
Thus protecting their system from individuals who may perform nefarious deeds when logged into or connected to the same WiFi network as their goggles.
> WiFi Module: added 3rd Page to configure System Options

- src/core/input_device.c
Changing the SDL user input detection from poll to wait significantly reduces the emulators CPU usage.
I don't know if there was a reason why poll was chosen initially but wait seems to work fine.
> Reduce emulator CPU usage

- lib/log/src/log.c
- src/core/app_state.c
- src/core/dvr.c
- src/core/settings.c
- src/core/thread.c
- src/driver/hardware.c
- src/record/avshare.c
- src/ui/page_playback.c
- src/ui/page_storage.c
- src/ui/page_version.c
- src/ui/page_wifi.c
- src/util/file.c
- src/util/file.h
- src/util/system.c
- src/util/system.h
Logger now writes to a cache prior to offloading the entries to the SD Card.  The interval of offloading the cache to disk is done once a second.  This caching allows us to continue to log during the integrity check when booting up the goggles or inserting a disk and once the sd card is available then we offload to the disk.  The max size of the cache is 1 MByte, then a rollover is performed.  This will allow users who may encounter errors during flight or bench testing to turn on logging via the Storage Page and we will have a complete capture of all messages since bootup.
We also now log system commands:
system_exec() is intended for one-line commands
system_script() is intended for invoking shell scripts, the standard output/error are also logged if any are produced.
> Logging framework now supports caching of entries during integrity check

- src/core/osd.c
After adjustment, the order of the antennas osd(7/8/9/10) is the same as the manual.
> adjust ANT OSD order

- src/core/main.c
- src/driver/hardware.c
- src/driver/hardware.h
- src/ui/page_power.c
- src/ui/page_sleep.c
- src/ui/page_source.c
This PR replaces the AnalogRX Power setting "Off" with "Auto" and adds a function to track/set analog module bay power only on state change. Currently this will beep on every commanded state change except initiation of Go Sleep! function.
WARNING!
This should read like a very familiar hangup with implementing a physical power switch. Adding this feature is important. However, creating any system to change the power state of a critical item introduces potential risk. So, This needs to be heavily tested prior to usage with remote equipment and commit of this PR into master.
Known issues while AnalogRX Power is set to "On":
-none this is similar to batch 1 goggle behavior
Known issues while AnalogRX Power is set to "Auto":
-Source page will report Expansion Module: Disconnected when …
> AnalogRX Power "Auto" -batch 2 goggle

- src/ui/page_storage.c
- src/util/sdcard.c
- src/util/sdcard.h
Add block device exist check instead of sdcard mounted check. Now googles can format sdcards with unsupported file system to FAT32. 
Large capacity sd cards has exFat file system by default.
By the way, it would be nice to add support for exFat and ext4 in future releases.
> Enable formatting not mounted sdcards

- src/core/osd.c
- src/core/settings.c
- src/core/settings.h
- src/ui/page_focus_chart.c
- src/ui/page_osd.c
- src/ui/ui_porting.c
- src/ui/ui_porting.h
- src/ui/ui_statusbar.c
Performs two levels of orbiting the OSD in order to minimize screen burn-in and static image retention.
> OLED burnin and static image protection

- src/core/app_state.h
- src/core/input_device.c
- src/ui/page_fans.c
- src/ui/page_fans.h
- src/ui/page_headtracker.c
- src/ui/page_headtracker.h
- src/ui/page_power.c
- src/ui/page_power.h
As stated in [app_state.h:27](https://github.com/hd-zero/hdzero-goggle/blob/b1c7d90f0dc3db1aa27b2d7cb3bc7051a45df158/src/core/app_state.h#L27), "pages should set the on_roller callback and handle the input themselves [...]".
This PR updates the corresponding pages' compile units to do that and removes the enum entries from the app_state header. It should be purely cosmetical and shouldn't change any behavior.
Tested my changes with a set of batch 2 goggles and couldn't find any unexpected behavior - however another one testing it would be appreciated.
> Let pages handle roller interaction

- src/ui/ui_statusbar.c
UI Status bar will now display "Format SD Card" when card is inserted but not mounted due to not being formatted with FAT32.
> Notify user SD Card requires formatting

- src/core/input_device.c
- src/ui/page_fans.c
Updates the menu UI when stepping the top fan value via the right button long press method as described in the issue.
Closes #352
> Update top fan slider when changing speed from video

- src/ui/page_wifi.c
By setting dns and wins to 0.0.0.0 android devices will be able to maintain connectivity with goggles and not disconnect due to no internet access.
> Fix for android devices to be able to maintain connection with goggles.

- src/ui/page_scannow.c
In the scan page, the description lacks a whitespace after the comma in the first line.
> Add missing whitespace

- mkapp/app/setting.ini
- src/core/common.hh
- src/core/dvr.c
- src/core/dvr.h
- src/core/input_device.c
- src/core/input_device.h
- src/core/osd.c
- src/core/osd.h
- src/core/settings.c
- src/core/settings.h
- src/driver/oled.h
- src/ui/page_fans.c
- src/ui/page_fans.h
- src/ui/page_input.c
- src/ui/page_input.h
- src/ui/page_sleep.c
- src/ui/ui_image_setting.c
- src/ui/ui_image_setting.h
- src/ui/ui_main_menu.c
This adds a page in the settings where one can freely assign the actions that are executed when a button or the roller is operated in video mode.
I also added the ability to change the top fan speed and the OLED brightness level with the roller.
When changing a channel is requested, the left short button acts as the "Enter" button, regardless of which action is configured for it.
**Note:** This changes the behavior introduced with #348 where I double-assigned the double right click for either HT Center or Go Sleep! mode. However, as this PR is not yet in the release candidate, I think, this shouldn't do much harm. Closes #357 
The available actions are for the roller:
- Switch channel
- Change fan speed
- OLED brightness
and for the buttons:
- Toggle OSD
- Main menu
- Toggle DVR
- Center …
> Make button and roller actions configurable for video mode

- src/ui/page_autoscan.c
- src/ui/page_common.c
- src/ui/page_common.h
- src/ui/page_elrs.c
- src/ui/page_fans.c
- src/ui/page_headtracker.c
- src/ui/page_power.c
- src/ui/page_record.c
- src/ui/page_storage.c
- src/ui/page_wifi.c
- src/ui/ui_main_menu.c
This PR improves the user experience when configuring the goggles. It adds kind of an `enabled` state for configuration items. That means, when an item is configured to be disabled, navigation skips this item and its text is displayed in a darker shade.
Further, when the first item in a page is disabled or only a label (for which the selection item should be set to disabled), it is skipped when entering that page.
In detail the following pages' configuration items are affected:
- Power
- `Battery` cell label is not selectable
- `Cell Count` slider can only be modified if `Cell Count Mode` is `Manual`
- Fans
- `Side Fans` slider can only be modified if `Auto Control` is `Off`
- Record Option
- `Audio Source` can only be switched if `Record Audio` is `On`
- Auto Scan
- `Default` selection …
> Improve configuration user experience

- src/driver/TP2825.c
Disabling back color killer feature on analog, that lead to smoother analog experience: no suddens loss of colors
> Analog disable color kill feature on TP2825

- .devcontainer/Dockerfile
Simple addition of SDL2 development resources allows me to build the software on MacOS with the support of XQuartz.
MacOS Instructions:
brew install --cask xquartz
XQuartz.app Settings [Located in /Applications/Utilities/]:
Enable "Allow connections from network clients"
XQuartz Terminal Commands:
```
defaults write org.xquartz.X11 enable_iglx -bool YES
```
Verify configuration was successfully applied
```
defaults read org.xquartz.X11 enable_igl
1
```
Reboot Mac!!!!
Now you can run emulator via docker and be sure XQuartz is running first.
```
./HDZGOGGLE
```
> Docker update for Emulator development

- lib/log/src/log.c
Will help in debugging how frequently an event occurs such as the button presses and allow us to fine tune the input handling parameters as needed.
```
2024-01-31 00:46:41.945 [INFO][hardware.c:HDZero_open:210] HDZero: open
2024-01-31 00:46:42.130 [INFO][page_scannow.c:scan_channel:309] Scan band:0, channel0: valid:0, gain:61
2024-01-31 00:46:42.644 [INFO][page_scannow.c:scan_channel:309] Scan band:0, channel1: valid:0, gain:61
2024-01-31 00:46:43.227 [INFO][page_scannow.c:scan_channel:309] Scan band:0, channel2: valid:0, gain:61
2024-01-31 00:46:43.710 [INFO][page_scannow.c:scan_channel:309] Scan band:0, channel3: valid:0, gain:61
2024-01-31 00:46:43.921 [INFO][page_scannow.c:scan_channel:309] Scan band:0, channel4: valid:0, gain:61
2024-01-31 00:46:44.492 …
```
> Timestamp log entries with millisecond resolution

- src/core/elrs.c
- src/core/ht.c
- src/core/ht.h
- src/core/main.c
- src/core/settings.c
- src/core/settings.h
- src/core/thread.c
- src/ui/page_headtracker.c
I was having issues with looking at the ground, so decided to create a feature that lets you select an angle at which it should start beeping.
I made a sub page in the head tracker page for the alarm. 
You can choose to turn the alarm off, put it in video mode where it will beep when you have signal, or in arm mode where it will beep when you are armed (this is using ELRS backpack Rec packet to see if the quad is armed or not.)
The set tilt alarm option is where you select at what angle you want it to start beeping, just hold your head at that angle and click the button.
> Head Tilt Alarm

- src/ui/page_version.c
We now cleanup the fw select dialog when exiting due to holding click button down.
> Fixed firmware select exiting when holding down click button.

- src/record/record_definitions.h
- Store DVR files in folder /DCIM/100HDZRO/
- Extend index length to 4 (hdz_xxx to hdz_xxxx)
[Design rule for Camera File system (DCF)](https://en.wikipedia.org/wiki/Design_rule_for_Camera_File_system#Directory_and_file_structure)
> Follow DCF for DVR storage

- src/core/SDLaccess.h
- src/core/input_device.c
- src/core/main.c
- src/ui/ui_porting.c
The emulator would crash for me. This is either because SDL was not initialised before SDL_WaitEvent was called, or more likely because anothe thread was trying to use SDL at the same time. This fixes both by initialising SDL earlier and by setting up a mutex that locks access to SDL when the input thread works. 
**This affects the emulator only, it has no impact on running on the goggles**
> Fixing emulator bug #391

- src/ui/page_input.c
- src/ui/page_source.c
- src/ui/page_source.h
Simplified version of the quickswap input PR, this PR replaces the old #423. 
Added 2 options to the dropdown menu on the inputs page: `Toggle source` and `Cycle source`
Added the remark 'Toggle source' will switch between HDZero and Expansion module
Everything can be set on the inputs page, without the need of defining which option you want to use on a separate page.
See `Right short:` and `Right long:` in the below example:
> Add quickswap input options to inputs menu

- src/ui/page_source.c
A few `break;` lines were overlooked in the changes I made that got pushed with #433. I've added them again which should solve the issues as described by @nerdCopter. Sorry for the inconvenience!
> Bugfix for #433 - Add quickswap input options to inputs menu

- src/ui/page_wifi.c
Resolves issue #432 where recording is initiated before wifi configuration has completed.  This is breakage introduced due to boot up optimization.
> Prevent recording race-condition when wifi is enabled

- src/ui/page_input.c
This PR adds the possibility to do nothing on specific input actions. I had to restructure how the input page is filled and handled in order to allow the new "None" function to be on top of all others. This opens the possibility to re-order the options and maybe regroup them in the future without impacting what a user has set in a previous version.
Quickly tested it in the emulator and it seems to be working as expected.
Closes #442
> Add possibility to select no action for inputs

- src/ui/page_playback.c
When using the roller in the playback page when it has only one DVR file, the highlight of that file would disappear. The reason for it was that the visibility flags were set on the new item before clearing them on the old item.
This change introduces an early return if both items in update_item are the same and wouldn't need a change in their visibility flags anyway.
> Fix disappearing navigation box when only one DVR is present

- src/ui/page_playback.c
Currently, when a user marks a clip as hot by right-clicking on a DVR in the playback page, the star will be lost.
This is because the thumbnail and video file get renamed but the star file doesn't.
> Fix star status is lost when marking clip as hot

- mkapp/app/setting.ini
- src/core/battery.c
- src/core/battery.h
- src/core/settings.c
- src/ui/page_power.c
- Show voltage as 0.00V/C instead of 0.0V/C. Also moved channel OSD to the right to accommodate longer voltage text
Emulator image (in goggles gap is smaller):
- Battery voltage warning and offset precision increased to 0.01V.
- To make code more consistent now variable `g_setting.power.voltage`, `g_battery.offset`, `WARNING_CELL_VOLTAGE_MIN` `WARNING_CELL_VOLTAGE_MAX`, `CALIBRATION_OFFSET_MIN`, `CALIBRATION_OFFSET_MAX` are in mV
I'm not sure how changing voltage units from 100mV to 1mV would effect user settings so before merging someone else should try this firmware and check if their saved warning and offset value was not corrupted after update
> Increase goggle battery voltage precision to 2 decimal places

- src/ui/page_wifi.c
This adds an "Apply Settings" button to all pages of the WiFi module settings.
All three buttons are synchronized and handled exactly the same so that when you change something on page 1, the buttons on pages 2 and 3 start flashing red as well and hitting any of them will trigger the confirmation and then the application action.
Closes #364
> Add "Apply Settings" button to all WiFi settings pages

- src/driver/hardware.c
It should have been merged into 9.4.0
> force av in clock phase

- src/driver/TP2825.c
This fixes the issue where the analog module displays other colors in the menu (which is only black and white).
> enable TP2825 color killer

- src/ui/page_storage.c
In attempt to fix #412, I added a call for updating the free sd card size to the formatting method. Unfortunately, @evilC was not able to reproduce and therefore confirm the fix, but I decided to give it a shot anyway.
Closes #412
> Update free SD card space after format

- src/ui/page_storage.c
This PR fixes the issue where recording fails after `Clear DVR Folder`.
> clear instead of delete dvr folder

- src/ui/page_storage.c
Please make sure that lvgl is called before mutex is executed.
> Fix the app crash when the first autoscan is completed after power on

- src/ui/page_common.h
When using `self_test.txt`, the source page has 10 options, which will cause the app to crash.
> set MAX_PANEKS to 10

- src/ui/page_clock.c
This bug will cause the program to crash when exiting the clock page if you use Chinese. I don't understand why there is no problem with English.
> Fix clock page item type

- src/core/app_state.c
- src/core/dvr.c
- src/core/msp_displayport.h
- src/core/thread.c
- src/driver/hardware.c
- src/driver/hardware.h
When goggle displays HDMI in, if the SD card exists and has more than 100MB of remaining storage, it will automatically record.
- h264 encoding
- 34 mbps
- TS format only
I tested:
- 1080p30
- 1080p50
- 1080p60
- 720p50
- 720p60
- 720p90
- 720p100*
Note that HDMI in 720p100 will be recorded at 720p90.
> Automatic recording HDMI in

- src/driver/dm6302.c
Increase the i2c speed when DM6302 is initialized and restore it after initialization.
The initialization time is reduced by about 40% to 50%. You can check it through the progress bar when entering image setting.
> Reduce the time consumed by HDZero RF initialization

- src/core/main.c
- src/driver/hardware.c
> do not check hdmi in source if quickly enter hdmi in mode after power on

- src/core/input_device.c
This problem may cause app initialization failure if the roller is used during power-on initialization.
> disable roller before init done

- src/core/common.c
- src/core/common.hh
- src/core/main.c
- src/core/thread.c
- src/ui/page_storage.c
- src/ui/page_storage.h
- src/ui/page_wifi.c
- src/ui/ui_main_menu.c
Fixed a few issues where the refactor of post bootup actions caused breakage.
1. SD Card repair thread needs to complete prior to invoking next boot action, thus we need to hold onto the bootup_complete_cb to invoke when thread is finished.
2. Sorting is now working as we need to apply indirection when passing pointers as arguments.
3. Preventing SD Card repair from running twice at bootup.  People should notice the SD Card becoming available at half the previous amount of time.
> Fix post bootup action

- src/ui/page_wifi.c
Title says it all.... we can now achieve close to 5.5MB/s when goggle is running as host.
Top terminal is the goggles running iperf3 as a server.
Bottom terminal is the macbook running iperf3 as a client.
> Enable 802.11n support for double the bandwidth when running as host.

- src/core/dvr.c
- src/core/settings.c
- src/core/settings.h
- src/ui/page_record.c
This change allows lowering the bitrate for the video recording.
The user can now set the bitrate to either: normal, 1/2, 1/4
Since the default bitrate changes according to the resolution and framerate, setting a static bitrate would not make sense.
Therefore I chose to allow configuration in fractions of the original bitrate.
Screenshot:
> dvr: make bitrate configurable

- .gitignore
- README.md
- flake.lock
- flake.nix
- mkapp/mkapp_ota.sh
- nix/devShell.nix
- nix/goggle-app.nix
- nix/toolchain.nix
This allows developers with a linux machine or docker or wsl to build
the app via this command.
```nix
nix build .#goggle-app
```
Except the nix package manager, no other tools need to be installed and
no environment needs to be set up.
The nix build system is quite flexible and has a rich ecosystem.
In the future, the nix declarations could be extended in order to:
- add automated testing to the build pipeline
- switch to a recent toolchain instead of the outdated one from 2018
currently pulled in by `setup.sh`
- cleanup the repo from binary files like busybox, tinycurl, dropbear,
etc. Instead declare dependencies through its source and build
definition, which simplifies updating, modifying and adding stuff.
- update the currently used 4.9.X linux kernel which is end-of-life
since 2023 …
> add declarative firmware build via nix

- mkapp/app/language/es_es.ini
Spanish variants of source page wording updates in PR #525 & #528 as provided by @mauriciobridge
Signal detected = "Señal detectada"
No signal = "Sin señal"
Analog input requires Expansion Module = "Entrada análoga requiere Módulo de Expansión"
> Update es_es.ini -Spanish source page wording update

- .github/workflows/build_and_release_boxpro.yml
- .github/workflows/build_and_release_goggle.yml
- setup.sh
updates to setup.sh script will now:
-prompt the source code user before downloading tool chain (~50mb)
-add verbosity for download and extraction status
-preserve downloaded tool chain .tar.bz2 file for future use
-allow user to pass full path of tool chain file or manually copy tool chain file into root of source to prevent prompting or new download of tool chain
launch with "automated_build for automated build environments. eg:
./setup.sh automated_build
These changes potentially reduce network data usage, increase tool chain portability during toolchains.bootlin.com service interruptions (~2025-06-21), and promote general awareness of source code users.
> Update setup.sh -add toolchain awareness

- src/core/settings.c
old rf_channel 6 is susceptible to interference.
> modify default wifi rf_channel to 11
